
const actions={

   TOGGLE_THEME:"TOGGLE_THEME",
   SET_DATA_PRODUCTOS:"SET_DATA_PRODUCTOS",
   SET_DATA_PRODUCTOS_PAGE:"SET_DATA_PRODUCTOS_PAGE",
   SET_LOADING:"SET_LOADING"



}

export {actions};