server:
  port: ${PORT:80}
spring:
   application:
      name: backend-is2
   datasource:
      url: jdbc:mysql://${DB_HOST}:3306/productos   
      username: ${DB_USER}
      password: ${DB_PASSWORD}
   jpa:
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
