spring:
   application:
      name: backend-is2
   datasource:
      url: jdbc:mysql://ds-mysql-aws.cmmzcyenln2y.us-east-2.rds.amazonaws.com:3306/productos   
      username: ${DB_USER}
      password: ${DB_PASSWORD}
   jpa:
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
